# This file was generated by GoReleaser. DO NOT EDIT.
cask "gctx" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "a8f8576fcb0492c4ba8c687d817c8720e2de7f7f8701f0455badaf0be4cddb4d"
      url "https://github.com/Poimidorka/gctx/releases/download/v#{version}/gctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "43a57b2e881375d4058f282bfb8ebc3a120209a077fa15da90dd4546b43dde76"
      url "https://github.com/Poimidorka/gctx/releases/download/v#{version}/gctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87d41e7b1e29bd31c8f793559df726b6a7624a8fe3adfebc58953d8cea04f467"
      url "https://github.com/Poimidorka/gctx/releases/download/v#{version}/gctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31a334205d0db6003d4470fa6b2692e46eea3d9c2b4bd92cd62abdd8dc014d7f"
      url "https://github.com/Poimidorka/gctx/releases/download/v#{version}/gctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gctx"
  desc "Small Git context switcher"
  homepage "https://github.com/Poimidorka/gctx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gctx"

  # No zap stanza required

end
